name = "nightpermit/cardano"
version = "0.1.0"
compiler = "v1.1.13"
plutus = "v3"
license = "Apache-2.0"
description = "Cardano Preview validator and Permit V1 decoder for NightPermit"

[repository]
user = "Minhcardanian"
project = "CaNi_mlh"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.1"
source = "github"

[config]
